Fix "cb is not a function" error
Extraction of RTF files would previously fail with `TypeError`: "cb is not a function".

This issue was caused by `html.extractFromText()` accepting an `options` object between the `data` and `cb` parameters (see [html.js:38](https://github.com/dbashford/textract/blob/416c55bf151c6ebe3cb8286c023e6fa10eaaa6df/lib/extractors/html.js#L38)) and `rtf.js` called it without the `options` parameter, resulting in `cb` being set to `undefined`.